### PR TITLE
feat:  Add support for localhost

### PR DESCRIPTION
**Pull request by GordonSmith**
Added some future-proofing for ECL Notebooks

Signed-off-by: Gordon Smith <GordonJSmith@gmail.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@HWatanuki please review.

This starts a local instance of the platform (which also includes the client tools), which can be targeted via the additional launch config.

Note:  The latest ECL Extension for VS Code can show results from non https environments when hosted on gitpod.

**Comment by GordonSmith** [comment]
@HWatanuki - I put together a similar repo for a generic ECL Playground:  https://github.com/GordonSmith/ECL-Playground

**Comment by HWatanuki** [comment]
@GordonSmith  - Thanks, I have reviewed/tested the changes and they work ok. Great idea on adding support for local host, BTW! I have incorporated the latest ECL Extension for VS Code so we can show results from non https environments when hosted on gitpod (thanks so much for accommodating this!). Specifically for the Comm Day workshop, I haven´t merged the support for localhost yet as, during the workshop, we are relying on data previously sprayed into a HMS cluster and I am afraid that some workshop participants may get confuse trying to use the localhost instead. As soon as the Comm Day workshop is over I will merge the localhost support as well.

**Comment by GordonSmith** [comment]
@HWatanuki - that sounds very sensible!

**Pull request merged**
